/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StagiaireRouteImport } from './routes/stagiaire'
import { Route as StageRouteImport } from './routes/stage'
import { Route as OutilsRouteImport } from './routes/outils'
import { Route as EmployeRouteImport } from './routes/employe'
import { Route as EmploiRouteImport } from './routes/emploi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QrEmployeEmployeIdRouteImport } from './routes/qr-employe.$employeId'
import { Route as FormulaireFormulaireIdRouteImport } from './routes/formulaire.$formulaireId'

const StagiaireRoute = StagiaireRouteImport.update({
  id: '/stagiaire',
  path: '/stagiaire',
  getParentRoute: () => rootRouteImport,
} as any)
const StageRoute = StageRouteImport.update({
  id: '/stage',
  path: '/stage',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsRoute = OutilsRouteImport.update({
  id: '/outils',
  path: '/outils',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeRoute = EmployeRouteImport.update({
  id: '/employe',
  path: '/employe',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploiRoute = EmploiRouteImport.update({
  id: '/emploi',
  path: '/emploi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrEmployeEmployeIdRoute = QrEmployeEmployeIdRouteImport.update({
  id: '/qr-employe/$employeId',
  path: '/qr-employe/$employeId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulaireFormulaireIdRoute = FormulaireFormulaireIdRouteImport.update({
  id: '/formulaire/$formulaireId',
  path: '/formulaire/$formulaireId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emploi': typeof EmploiRoute
  '/employe': typeof EmployeRoute
  '/outils': typeof OutilsRoute
  '/stage': typeof StageRoute
  '/stagiaire': typeof StagiaireRoute
  '/formulaire/$formulaireId': typeof FormulaireFormulaireIdRoute
  '/qr-employe/$employeId': typeof QrEmployeEmployeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emploi': typeof EmploiRoute
  '/employe': typeof EmployeRoute
  '/outils': typeof OutilsRoute
  '/stage': typeof StageRoute
  '/stagiaire': typeof StagiaireRoute
  '/formulaire/$formulaireId': typeof FormulaireFormulaireIdRoute
  '/qr-employe/$employeId': typeof QrEmployeEmployeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emploi': typeof EmploiRoute
  '/employe': typeof EmployeRoute
  '/outils': typeof OutilsRoute
  '/stage': typeof StageRoute
  '/stagiaire': typeof StagiaireRoute
  '/formulaire/$formulaireId': typeof FormulaireFormulaireIdRoute
  '/qr-employe/$employeId': typeof QrEmployeEmployeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emploi'
    | '/employe'
    | '/outils'
    | '/stage'
    | '/stagiaire'
    | '/formulaire/$formulaireId'
    | '/qr-employe/$employeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emploi'
    | '/employe'
    | '/outils'
    | '/stage'
    | '/stagiaire'
    | '/formulaire/$formulaireId'
    | '/qr-employe/$employeId'
  id:
    | '__root__'
    | '/'
    | '/emploi'
    | '/employe'
    | '/outils'
    | '/stage'
    | '/stagiaire'
    | '/formulaire/$formulaireId'
    | '/qr-employe/$employeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmploiRoute: typeof EmploiRoute
  EmployeRoute: typeof EmployeRoute
  OutilsRoute: typeof OutilsRoute
  StageRoute: typeof StageRoute
  StagiaireRoute: typeof StagiaireRoute
  FormulaireFormulaireIdRoute: typeof FormulaireFormulaireIdRoute
  QrEmployeEmployeIdRoute: typeof QrEmployeEmployeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stagiaire': {
      id: '/stagiaire'
      path: '/stagiaire'
      fullPath: '/stagiaire'
      preLoaderRoute: typeof StagiaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage': {
      id: '/stage'
      path: '/stage'
      fullPath: '/stage'
      preLoaderRoute: typeof StageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils': {
      id: '/outils'
      path: '/outils'
      fullPath: '/outils'
      preLoaderRoute: typeof OutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employe': {
      id: '/employe'
      path: '/employe'
      fullPath: '/employe'
      preLoaderRoute: typeof EmployeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emploi': {
      id: '/emploi'
      path: '/emploi'
      fullPath: '/emploi'
      preLoaderRoute: typeof EmploiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-employe/$employeId': {
      id: '/qr-employe/$employeId'
      path: '/qr-employe/$employeId'
      fullPath: '/qr-employe/$employeId'
      preLoaderRoute: typeof QrEmployeEmployeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaire/$formulaireId': {
      id: '/formulaire/$formulaireId'
      path: '/formulaire/$formulaireId'
      fullPath: '/formulaire/$formulaireId'
      preLoaderRoute: typeof FormulaireFormulaireIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmploiRoute: EmploiRoute,
  EmployeRoute: EmployeRoute,
  OutilsRoute: OutilsRoute,
  StageRoute: StageRoute,
  StagiaireRoute: StagiaireRoute,
  FormulaireFormulaireIdRoute: FormulaireFormulaireIdRoute,
  QrEmployeEmployeIdRoute: QrEmployeEmployeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
